name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "DB_DSN=${{ secrets.DB_DSN }}" >> .env
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> .env
          echo "IS_DEVELOPMENT=${{ secrets.IS_DEVELOPMENT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Copy project files to EC2
        run: |
          rsync -avz --delete ./ ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/playground-dev/simple-withdraw-api

      - name: Deploy on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/playground-dev/simple-withdraw-api
            docker stop simple-app || true && docker rm simple-app || true
            docker build -t simple-app .
            docker run -d --name simple-app --env-file .env -p 6005:6005 simple-app
          EOF
